@startuml Gaviel Scheme

participant Writer
database WriterDatabase
entity QM
entity DH
database SQLServer
== Encrypt ==
Writer->DH: Encrypt(Database, keys)
activate Writer
activate DH
note right: Generating encrypted index\n of the database
DH->DH: GenerateIndex
deactivate Writer
deactivate DH

== Modifying Database ==
Writer -> DH : Register\n    ( tableName, attributes )
note left : CREATE TABLE Molecules \n (NAME CHAR(30),\n ATOM_NO INT,\n BOND_NO INT)
activate Writer
DH->SQLServer : CreateTable ( tableName, encrypted attributes )
note left SQLServer: CREATE TABLE IF NOT EXISTS\n _e1f90... \n (recordId INT,\n _17f3d0 VARCHAR(100),\n _a19855 VARCHAR(100),\n _523f88 VARCHAR(100))
deactivate Writer


Writer -> WriterDatabase : AddData(values)
note left: INSERT INTO Molecules\n(NAME, ATOM_NO, BOND_NO)\n VALUES ('1-Heptane', 0, 1)
activate Writer
Writer -> DH: updateDatabase(values)
activate DH

DH->SQLServer: getTableRecordLength (tableName)
activate SQLServer
note left SQLServer: SELECT * FROM _e1f90;
SQLServer-->DH: number of records
deactivate SQLServer

DH->SQLServer: insertIntoTable
note left SQLServer: INSERT OR IGNORE INTO _e1f90\n(recordId, _17f3d0,  _a19855, _523f88)\nVALUES (1, d3b35, 3da20, bd77d);
deactivate DH


alt RegenerateIndex=True
Writer->DH: EncryptIndex (Database, Keys)
activate DH
DH->DH: BuildIndex(Database, Keys)
deactivate Writer
end
deactivate DH